<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title>Partner Admin</title>
        <!-- Bootstrap framework -->
        <link rel="stylesheet" href="<?php echo _HPARTNER_URL; ?>/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="<?php echo _HPARTNER_URL; ?>/css/jquery-ui.css" />
        <!-- main styles -->
		<link rel="stylesheet" href="<?php echo _HPARTNER_URL; ?>/css/blue.css" />
        <link rel="stylesheet" href="<?php echo _HPARTNER_URL; ?>/css/style.css" />   
        <script src="<?php echo _HPARTNER_URL; ?>/js/jquery-1.9.1.js"></script>
        <!-- js cookie plugin -->
        <script src="<?php echo _HPARTNER_URL; ?>/js/jquery.cookie.min.js"></script>          
        <!-- main bootstrap js -->
        <script src="<?php echo _HPARTNER_URL; ?>/bootstrap/js/bootstrap.min.js"></script>
        <script src="<?php echo _HPARTNER_URL; ?>/js/jquery-ui.js"></script>

        <!-- CKEDITOR-->
        <script src="<?php echo _HPARTNER_URL; ?>/ckeditor/ckeditor.js" type="text/javascript"></script>
        <script src="<?php echo _HPARTNER_URL; ?>/ckeditor/adapters/jquery.js"></script>
        <script>
            $(document).ready(function() {
                //Quote
                $(".Editor_Body").each(function() {
                    CKEDITOR.replace($(this).attr('id'), {
                        toolbar: [
                            {name: 'document', items: ['Source', '-', 'NewPage', 'Preview', '-', 'Templates']}, // Defines toolbar group with name (used to create voice label) and items in 3 subgroups.
                            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'], // Defines toolbar group without name.
                            '/', // Line break - next group will be placed in new line.
                            {name: 'basicstyles', items: ['Bold', 'Italic']}
                        ]
                    });
                });
            });
        </script>
        <!-- script all js -->
        <script src="<?php echo _HPARTNER_URL; ?>/bootstrap/js/script-all.js"></script>
    </head>
    <body>
        <div id="loading_layer" style="display:none"><img src="<?php echo _HPARTNER_URL; ?>/img/ajax_loader.gif" alt="" /></div>
        <div class="style_switcher">
            <div class="sepH_c">
                <p>Colors:</p>
                <div class="clearfix">
                    <a href="javascript:void(0)" class="style_item jQclr blue_theme style_active" title="blue">blue</a>
                    <a href="javascript:void(0)" class="style_item jQclr dark_theme" title="dark">dark</a>
                    <a href="javascript:void(0)" class="style_item jQclr green_theme" title="green">green</a>
                    <a href="javascript:void(0)" class="style_item jQclr brown_theme" title="brown">brown</a>
                    <a href="javascript:void(0)" class="style_item jQclr eastern_blue_theme" title="eastern_blue">eastern blue</a>
                    <a href="javascript:void(0)" class="style_item jQclr tamarillo_theme" title="tamarillo">tamarillo</a>
                </div>
            </div>
            <div class="sepH_c">
                <p>Backgrounds:</p>
                <div class="clearfix">
                    <span class="style_item jQptrn style_active ptrn_def" title=""></span>
                    <span class="ssw_ptrn_a style_item jQptrn" title="ptrn_a"></span>
                    <span class="ssw_ptrn_b style_item jQptrn" title="ptrn_b"></span>
                    <span class="ssw_ptrn_c style_item jQptrn" title="ptrn_c"></span>
                    <span class="ssw_ptrn_d style_item jQptrn" title="ptrn_d"></span>
                    <span class="ssw_ptrn_e style_item jQptrn" title="ptrn_e"></span>
                </div>
            </div>
            <div class="sepH_c">
                <p>Layout:</p>
                <div class="clearfix">
                    <label class="radio inline"><input type="radio" name="ssw_layout" id="ssw_layout_fluid" value="" checked /> Fluid</label>
                    <label class="radio inline"><input type="radio" name="ssw_layout" id="ssw_layout_fixed" value="gebo-fixed" /> Fixed</label>
                </div>
            </div>
            <div class="sepH_c">
                <p>Sidebar position:</p>
                <div class="clearfix">
                    <label class="radio inline"><input type="radio" name="ssw_sidebar" id="ssw_sidebar_left" value="" checked /> Left</label>
                    <label class="radio inline"><input type="radio" name="ssw_sidebar" id="ssw_sidebar_right" value="sidebar_right" /> Right</label>
                </div>
            </div>
            <div class="sepH_c">
                <p>Show top menu on:</p>
                <div class="clearfix">
                    <label class="radio inline"><input type="radio" name="ssw_menu" id="ssw_menu_click" value="" checked /> Click</label>
                    <label class="radio inline"><input type="radio" name="ssw_menu" id="ssw_menu_hover" value="menu_hover" /> Hover</label>
                </div>
            </div>

            <div class="gh_button-group">
                <a href="#" id="showCss" class="btn btn-primary btn-mini">Show CSS</a>
                <a href="#" id="resetDefault" class="btn btn-mini">Reset</a>
            </div>
            <div class="hide">
                <ul id="ssw_styles">
                    <li class="small ssw_mbColor sepH_a" style="display:none">body {<span class="ssw_mColor sepH_a" style="display:none"> color: #<span></span>;</span> <span class="ssw_bColor" style="display:none">background-color: #<span></span> </span>}</li>
                    <li class="small ssw_lColor sepH_a" style="display:none">a { color: #<span></span> }</li>
                </ul>
            </div>
        </div>

        <div id="maincontainer" class="clearfix">
            <!-- header -->
            <header>
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container-fluid">
                            <a class="brand" href="<?php echo _URL_HPARTNER; ?>"><i
                                    class="icon-home icon-white"></i> Partner Admin</a>
                            <ul class="nav user_menu pull-right">							
                                <li class="divider-vertical hidden-phone hidden-tablet"></li>
                                <li class="dropdown"><a href="#" class="dropdown-toggle"
                                                        data-toggle="dropdown"><?php echo $this->UserPartner['User_Name']; ?> <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo _URL_HPARTNER; ?>/logout">Đăng xuất</a></li>
                                    </ul></li>
                            </ul>
                            <a data-target=".nav-collapse" data-toggle="collapse"
                               class="btn_menu"> <span class="icon-align-justify icon-white"></span>
                            </a>						
                        </div>
                    </div>
                </div>		
            </header>            
            <!-- main content -->
            <div id="contentwrapper">
                <div class="main_content">
                    <?php echo $this->layout()->content; ?>                    
                </div>

                <!-- sidebar -->
                
                <div class="sidebar">
                    <div class="antiScroll">
                        <div class="antiscroll-inner">
                            <div class="antiscroll-content">
                                <div class="sidebar_inner">
                                    <div id="side_accordion" class="accordion">
                                        <div class="accordion-group">
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle"> <i
                                                        class="icon-star"></i> Hồ sơ khách sạn
                                                </a>
                                            </div>
                                            <div class="accordion-body in collapse" id="collapseOne">
                                                <div class="accordion-inner">
                                                    <ul class="nav nav-list">
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-profile">Thông tin khách sạn</a></li>
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-map">Bản đồ</a></li>	
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-facilities">Tiện nghi</a></li>
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-picture">Hình ảnh</a></li>
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-room">Phòng</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="accordion-group">
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle"> <i
                                                        class="icon-star"></i> Cài đặt
                                                </a>
                                            </div>
                                            <div class="accordion-body in collapse" id="collapseTwo">
                                                <div class="accordion-inner">
                                                    <ul class="nav nav-list">
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-setup">Cài đặt khách sạn</a></li>                    
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-room-setup">Cài đặt phòng</a></li>
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-tax-setup">Thuế</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="accordion-group">
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle"> <i
                                                        class="icon-star"></i> Số phòng chỉ định và giá phòng
                                                </a>
                                            </div>
                                            <div class="accordion-body in collapse" id="collapseThree">
                                                <div class="accordion-inner">
                                                    <ul class="nav nav-list">
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-room-set">Biểu giá và phòng chỉ định</a></li>
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-room-management">Quản lý phòng</a></li>   
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-room-price-management">Quản lý giá phòng</a></li>
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-room-promotion">Khuyến mãi</a></li>
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/hotel-room-policy-cancel-set">Chính sách hủy phòng</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="accordion-group">
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle"> <i
                                                        class="icon-star"></i> Thống kê
                                                </a>
                                            </div>
                                            <div class="accordion-body in collapse" id="collapseThree">
                                                <div class="accordion-inner">
                                                    <ul class="nav nav-list">
                                                        <li><a href="<?php echo _URL_HPARTNER; ?>/order">Đặt phòng</a></li> 
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="push"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


            </div>
    </body>
</html>