<?php if (count($this->WarningMsg) > 0) { ?>
    <div class="warning_box">
        <?php echo current($this->WarningMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->SuccessMsg) > 0) { ?>
    <div class="valid_box">
        <?php echo current($this->SuccessMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->ErrorMsg) > 0) { ?>
    <div class="error_box">
        <?php echo current($this->ErrorMsg); ?>
    </div>
<?php } ?>
<div class="form">
    <form action="" method="post" class="niceform" name='frm' enctype="multipart/form-data">
        <fieldset>
            <dl>
                <dt><label for="email">Loại hình ảnh:</label></dt>
                <dd><input placeholder="Loại hình ảnh" type="text" name="Name" id="Name" size="34" class="require" value="<?php echo $this->PictureView['PictureView_Name']; ?>" /></dd>
            </dl>
            
            <dl>
                <dt><label for="color">Hiển thị</label></dt>
                <dd>
                    <input <?php echo ($this->PictureView['PictureView_Status'] == 1) ? "checked='checked'" : ""; ?> type="radio" name="Status" id="Status_1" value="1" checked="checked" /><label for="Status_1" class="check_label">Có</label>
                    <input <?php echo ($this->PictureView['PictureView_Status'] == 0) ? "checked='checked'" : ""; ?> type="radio" name="Status" id="Status_0" value="0" /><label for="Status_0" class="check_label">Không</label>
                </dd>
            </dl>

            <dl class="submit">
                <a onclick="checkForm()" class="bt_blue"><span class="bt_blue_lft"></span><strong>Cập nhật</strong><span class="bt_blue_r"></span></a>
            </dl>
        </fieldset>
    </form>
</div>

<script>
        function checkForm() {
            var name = $("#Name").val();
            if (name == '') {
                alert('Vui lòng nhập Tên.');
                $("#Name").focus();
                return;
            }
            document.frm.submit();
        }
</script>