<?php if (count($this->WarningMsg) > 0) { ?>
    <div class="warning_box">
        <?php echo current($this->WarningMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->SuccessMsg) > 0) { ?>
    <div class="valid_box">
        <?php echo current($this->SuccessMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->ErrorMsg) > 0) { ?>
    <div class="error_box">
        <?php echo current($this->ErrorMsg); ?>
    </div>
<?php } ?>
<div class="form">
    <form action="" method="post" class="niceform" name='frm' enctype="multipart/form-data">
        <fieldset>
            <dl>
                <dt><label for="email">Tên Quận/Huyện:</label></dt>
                <dd><input placeholder="Quận/Huyện" type="text" name="Name" id="Name" size="34" class="require" value="<?php echo $this->District['District_Name']; ?>" /></dd>
            </dl>
            <dl>
                <dt><label>Thuộc Tỉnh/Thành:</label></dt>
                <dd>
                    <select name='Province'>
                        <option></option>
                        <?php foreach($this->listProvince as $v) {?>
                        <option <?php echo ($this->District['Province_Id'] == $v['Province_Id']) ? "selected='selected'" : "" ;?> value="<?php echo $v['Province_Id'];?>"><?php echo $v['Province_Name'];?></option>
                        <?php }?>
                    </select>
                </dd>
            </dl>

            <dl>
                <dt><label for="color">Hiển thị</label></dt>
                <dd>
                    <input <?php echo ($this->District['District_Status'] == 1) ? "checked='checked'" : ""; ?> type="radio" name="Status" id="Status_1" value="1" checked="checked" /><label for="Status_1" class="check_label">Có</label>
                    <input <?php echo ($this->District['District_Status'] == 0) ? "checked='checked'" : ""; ?> type="radio" name="Status" id="Status_0" value="0" /><label for="Status_0" class="check_label">Không</label>
                </dd>
            </dl>

            <dl class="submit">
                <a onclick="checkForm()" class="bt_blue"><span class="bt_blue_lft"></span><strong>Cập nhật</strong><span class="bt_blue_r"></span></a>
            </dl>
        </fieldset>
    </form>
</div>

<script>
        function checkForm() {
            var name = $("#Name").val();
            if (name == '') {
                alert('Vui lòng nhập Tên.');
                $("#Name").focus();
                return;
            }
            document.frm.submit();
        }
</script>