          
<?php if (count($this->WarningMsg) > 0) { ?>
    <div class="warning_box">
        <?php echo current($this->WarningMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->SuccessMsg) > 0) { ?>
    <div class="valid_box">
        <?php echo current($this->SuccessMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->ErrorMsg) > 0) { ?>
    <div class="error_box">
        <?php echo current($this->ErrorMsg); ?>
    </div>
<?php } ?>       

<form action="<?php echo _URL_ADMIN . '/hotel-district/delete'; ?>" name='frm' method='post'>
    <table id="rounded-corner">
        <thead>
            <tr>
                <th scope="col" class="rounded-company"><input type="checkbox" name="checkAll" id="checkAll" value="" /></th>
                <th scope="col" class="rounded">Quận/Huyện</th>
                <th scope="col" class="rounded">Tỉnh/Thành</th>
                <th scope="col" class="rounded">Trạng thái</th>
                <th scope="col" class="rounded">Sửa</th>
                <th scope="col" class="rounded-q4">Xóa</th>
            </tr>
        </thead>
        <?php if (count($this->listDistrict) > 0) { ?>
            <tfoot>
                <tr>
                    <td colspan="5" class="rounded-foot-left"><em>Hiển thị <?php echo $this->fromItem; ?> đến <?php echo $this->toItem; ?> / <?php echo $this->countDistrictAll; ?> kết quả</em></td>
                    <td class="rounded-foot-right">&nbsp;</td>

                </tr>
            </tfoot>
            <tbody>
                <?php foreach ($this->listDistrict as $v) { ?>
                    <tr>
                        <td><input type="checkbox" name="checkboxDel[]" value="<?php echo $v['District_Id']; ?>" /></td>
                        <td><?php echo $v['District_Name']; ?></td>
                        <td><?php echo $v['Province_Name']; ?></td>
                        <td>
                            <img class="status-img" id="status_<?php echo $v['District_Id']; ?>" 
                                 onclick="updateStatus(<?php echo $v['District_Id']; ?>)" 
                                 src="<?php echo _BACKEND_URL . '/images/' . (($v['District_Status'] == 1) ? 'icon_approve.png' : 'icon_unapprove.png'); ?>" />
                        </td>
                        <td><a href="<?php echo _URL_ADMIN . '/hotel-district/edit/id/' . $v['District_Id']; ?>"><img src="<?php echo _BACKEND_URL; ?>/images/user_edit.png" alt="" title="" border="0" /></a></td>
                        <td><a href="<?php echo _URL_ADMIN . '/hotel-district/delete/id/' . $v['District_Id']; ?>" class="ask"><img src="<?php echo _BACKEND_URL; ?>/images/trash.png" alt="" title="" border="0" /></a></td>
                    </tr>
                <?php } ?>
            </tbody>
        <?php } else { ?>
            <tr>
                <td colspan="6" class="result">
                    <div class='no-result'>Không tìm thấy kết quả</a>
                </td>
            </tr>
        <?php } ?>
    </table>
</form>
<a href="<?php echo _URL_ADMIN . '/hotel-district/add'; ?>" class="bt_green"><span class="bt_green_lft"></span><strong>Thêm</strong><span class="bt_green_r"></span></a>
<a onclick="checkForm()" class="bt_red"><span class="bt_red_lft"></span><strong>Xóa</strong><span class="bt_red_r"></span></a> 
        <?php echo $this->paginationControl($this->page, 'Sliding', 'page.phtml', array('controller' => 'hotel-district')); ?>

<script>
                             function checkForm() {
                                 var checkValue = $("input[name='checkboxDel[]']:checked").length;
                                 if (checkValue == 0) {
                                     alert('Vui lòng chọn dòng cần xóa.');
                                     return false;
                                 }
                                 if (confirm('Bạn có chắc chắn muốn xóa?')) {
                                     document.frm.submit();
                                 }
                             }

                             function updateStatus(id) {
                                 $.post('<?php echo _URL_ADMIN . '/hotel-district/updatestatus/'; ?>', {id: id, table: '<?php echo _PREFIX; ?>hotel_district', statusName: 'District_Status', idName: 'District_Id'}, function(result) {
                                     if (result == 1) {
                                         $("#status_" + id).attr("src", "<?php echo _BACKEND_URL . '/images/icon_approve.png'; ?>");
                                     } else {
                                         $("#status_" + id).attr("src", "<?php echo _BACKEND_URL . '/images/icon_unapprove.png'; ?>");
                                     }
                                 })
                             }
</script>