<div class="row-fluid">
    <div class="span12">
        <h3 class="heading">Danh sách doanh nghiệp</h3>
        <table class="table table-bordered table-striped table_vam" id="dt_enterprises">
            <thead>
                <tr>
                    <th class="table_checkbox"><input type="checkbox" name="select_rows" class="select_rows" data-tableid="dt_enterprises" /></th>
                    <th style="width:200px">Tên doanh nghiệp</th>
                    <th style="width:150px">Tình trạng</th>
                    <th style="width:300px">Địa chỉ</th>
                    <th style="width:100px">Số điện thoại</th>
                    <th style="width:150px">Email</th>
                    <th style="width:200px">Websites</th>
                    <th style="width:200px">Thông tin doanh nghiệp</th>
                    <th>Tùy chọn</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="row_sel" class="row_sel" /></td>
                    <td style="width:60px">Payoo</td>
                    <td>Đang hợp tác</td>
                    <td>9 Đinh Tiên Hoàng</td>
                    <td>09123456789</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <a href="#" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        <a href="#" class="sepV_a" title="Xem chi tiết"><i class="icon-eye-open"></i></a>
                        <a href="#" title="Xóa"><i class="icon-trash"></i></a>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
</div>

<!-- hide elements (for later use) -->
<div class="hide">
    <!-- actions for datatables -->
    <div class="dt_enterprises_actions">
        <div class="btn-group">
            <button data-toggle="dropdown" class="btn dropdown-toggle">Tùy chọn<span class="caret"></span></button>
            <ul class="dropdown-menu">
                <li><a href="#" class="delete_rows_dt" data-tableid="dt_enterprises"><i class="icon-trash"></i> Xóa</a></li>									
            </ul>
        </div>
    </div>
    <!-- confirmation box -->
    <div id="confirm_dialog" class="cbox_content">
        <div class="sepH_c tac"><strong>Bạn chắc chắn muốn xóa (các) dòng này?</strong></div>
        <div class="tac">
            <a href="#" class="btn btn-gebo confirm_yes">Vâng</a>
            <a href="#" class="btn confirm_no">Không</a>
        </div>
    </div>

</div>