          
<?php if (count($this->WarningMsg) > 0) { ?>
    <div class="warning_box">
        <?php echo current($this->WarningMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->SuccessMsg) > 0) { ?>
    <div class="valid_box">
        <?php echo current($this->SuccessMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->ErrorMsg) > 0) { ?>
    <div class="error_box">
        <?php echo current($this->ErrorMsg); ?>
    </div>
<?php } ?>      

<form name="frsearch" action="<?php echo _URL_ADMIN . '/hotel-room'; ?>" method="post">
    <fieldset class="fr-search">
        <legend>Tìm kiếm</legend>
        <table>
            <tr>
                <td style="width: 70px;" align="right">Khách sạn</td>
                <td>
                    <select name="HotelSearch">
                        <option value="">Tất cả</option>
                        <?php foreach ($this->Hotel as $v) { ?>
                            <option <?php echo ($this->search['HotelSearch'] == $v['Hotel_Id']) ? "selected='selected'" : ""; ?> value="<?php echo $v['Hotel_Id']; ?>"><?php echo $v['Hotel_Name']; ?></option>
                        <?php } ?>
                    </select>
                </td>
                <td align="right">Trạng thái</td>
                <td>
                    <select name="StatusSearch">
                        <option value="">Tất cả</option>
                        <option value="1" <?php echo ($this->search['StatusSearch'] == "1") ? "selected='selected'" : ""; ?>>Hoạt động</option>
                        <option value="0" <?php echo ($this->search['StatusSearch'] == "0") ? "selected='selected'" : ""; ?>>Tạm dừng</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <input type="hidden" name="typeAction" value="search" />
                    <a onclick="document.frsearch.submit()" class="bt_green"><span class="bt_green_lft"></span><strong>Tìm kiếm</strong><span class="bt_green_r"></span></a>
                </td>
            </tr>
        </table>
    </fieldset>
</form>

<form action="<?php echo _URL_ADMIN . '/hotel-room/delete'; ?>" name='frm' method='post'>
    <input type="hidden" name="typeAction" value="index" />
    <table id="rounded-corner">
        <thead>
            <tr>
                <th scope="col" class="rounded-company"><input type="checkbox" name="checkAll" id="checkAll" value="" /></th>
                <th scope="col" class="rounded" align="center">STT</th>
                <th scope="col" class="rounded">Loại phòng</th>
                <th scope="col" class="rounded">Khách sạn</th>
                <th scope="col" class="rounded">Ngày tạo</th>
                <th scope="col" class="rounded">Trạng thái</th>
                <th scope="col" class="rounded">Sửa</th>
                <th scope="col" class="rounded-q4">Xóa</th>
            </tr>
        </thead>
        <?php if (count($this->listHotelRoom) > 0) { ?>
            <tfoot>
                <tr>
                    <td colspan="7" class="rounded-foot-left"><em>Hiển thị <?php echo $this->fromItem; ?> đến <?php echo $this->toItem; ?> / <?php echo $this->countHotelRoomAll; ?> kết quả</em></td>
                    <td class="rounded-foot-right">&nbsp;</td>

                </tr>
            </tfoot>
            <tbody>
                <?php
                $i = $this->fromItem;
                foreach ($this->listHotelRoom as $v) {
                    ?>
                    <tr>                 
                        <td><input type="checkbox" name="checkboxDel[]" value="<?php echo $v['Room_Id']; ?>" /></td>
                        <td align="center"><?php echo $i; ?></td>
                        <td><?php echo stripslashes($v['Room_Name']); ?></td>
						<td><?php echo stripslashes($v['Hotel_Name']); ?></td> 
                        <td><?php echo MyZend_Function::formatDateYMDHIS_DMYHIS($v['Room_Date_create']); ?></td>
                        <td>
                            <img class="status-img" id="status_<?php echo $v['Room_Id']; ?>" 
                                 onclick="updateStatus(<?php echo $v['Room_Id']; ?>)" 
                                 src="<?php echo _BACKEND_URL . '/images/' . (($v['Room_Status'] == 1) ? 'icon_approve.png' : 'icon_unapprove.png'); ?>" />
                        </td>
                        <td><a href="<?php echo _URL_ADMIN . '/hotel-room/edit/id/' . $v['Room_Id']; ?>"><img src="<?php echo _BACKEND_URL; ?>/images/user_edit.png" alt="" title="" border="0" /></a></td>
                        <td><a href="<?php echo _URL_ADMIN . '/hotel-room/delete/id/' . $v['Room_Id']; ?>" class="ask"><img src="<?php echo _BACKEND_URL; ?>/images/trash.png" alt="" title="" border="0" /></a></td>
                    </tr>
                    <?php $i++;
                }
                ?>
            </tbody>
<?php } else { ?>
            <tr>
                <td colspan="8" class="result">
                    <div class='no-result'>Không tìm thấy kết quả</a>
                </td>
            </tr>
<?php } ?>
    </table>
</form>
<a href="<?php echo _URL_ADMIN . '/hotel-room/add'; ?>" class="bt_green"><span class="bt_green_lft"></span><strong>Thêm</strong><span class="bt_green_r"></span></a>
<a onclick="checkForm()" class="bt_red"><span class="bt_red_lft"></span><strong>Xóa</strong><span class="bt_red_r"></span></a> 
<?php echo $this->paginationControl($this->page, 'Sliding', 'page.phtml', array('controller' => 'hotel-room')); ?>

<script>
                        function checkForm() {
                            var checkValue = $("input[name='checkboxDel[]']:checked").length;
                            if (checkValue == 0) {
                                alert('Vui lòng chọn dòng cần xóa.');
                                return false;
                            }
                            if (confirm('Bạn có chắc chắn muốn xóa?')) {
                                document.frm.submit();
                            }
                        }

                        function updateStatus(id) {
                            $.post('<?php echo _URL_ADMIN . '/hotel-room/updatestatus/'; ?>', {id: id, table: '<?php echo _PREFIX; ?>hotel_room', statusName: 'Room_Status', idName: 'Room_Id'}, function(result) {
                                if (result == 1) {
                                    $("#status_" + id).attr("src", "<?php echo _BACKEND_URL . '/images/icon_approve.png'; ?>");
                                } else {
                                    $("#status_" + id).attr("src", "<?php echo _BACKEND_URL . '/images/icon_unapprove.png'; ?>");
                                }
                            })
                        }
</script>