
<!-- Maps marker-->
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script>
// The following example creates a marker in Stockholm, Sweden
// using a DROP animation. Clicking on the marker will toggle
// the animation between a BOUNCE animation and no animation.

    var latDefault = 14.060154519818523;
    var lngDefault = 108.27189977929686;
    var zoomDefault = 5;

    function initialize() {
        getPosition();
        var vietnam = new google.maps.LatLng(lat, lng);
        var parliament = new google.maps.LatLng(lat, lng);
        var marker;
        var map;

        var mapOptions = {
            zoom: zoom,
            center: vietnam
        };

        map = new google.maps.Map(document.getElementById('map'),
                mapOptions);

        marker = new google.maps.Marker({
            map: map,
            draggable: true,
            animation: google.maps.Animation.DROP,
            position: parliament
        });

        // Create a DIV to hold the control and call HomeControl()
        var homeControlDiv = document.createElement('div');
        var homeControl = new HomeControl(homeControlDiv, map);
        map.controls[google.maps.ControlPosition.TOP_RIGHT].push(homeControlDiv);

        google.maps.event.addListener(marker, 'click', function(event) {
            toggleBounce();
        });
        google.maps.event.addListener(marker, 'dragend', function(event) {
            $("#lat").val(event.latLng.lat());
            $("#lng").val(event.latLng.lng());
            $("#zoom").val(map.getZoom());

        });

        google.maps.event.addDomListener(marker, 'zoom_changed', function(event) {
            alert('test');
            $("#zoom").val(map.getZoom());
        });
    }

    function toggleBounce() {
        if (marker.getAnimation() != null) {
            marker.setAnimation(null);
        } else {
            marker.setAnimation(google.maps.Animation.BOUNCE);
        }
    }
    //google.maps.event.addDomListener(window, 'load', initialize);

    function getPosition() {
        var latInput = $("#lat").val();
        var lngInput = $("#lng").val();
        var zoomInput = $("#zoom").val();

        lat = latDefault;
        lng = lngDefault;
        zoom = zoomDefault;

        if (latInput != "") {
            lat = latInput;
        }
        if (lngInput != "") {
            lng = lngInput;
        }
        if (zoomInput != "") {
            zoom = parseInt(zoomInput);
        }
    }

    // Add a Home control that returns the user to London
    function HomeControl(controlDiv, map) {
        homePosition = new google.maps.LatLng(latDefault, lngDefault);
        controlDiv.style.padding = '5px';
        var controlUI = document.createElement('div');
        controlUI.style.backgroundColor = 'yellow';
        controlUI.style.border = '1px solid';
        controlUI.style.cursor = 'pointer';
        controlUI.style.textAlign = 'center';
        controlUI.title = 'Set map to London';
        controlDiv.appendChild(controlUI);
        var controlText = document.createElement('div');
        controlText.style.fontFamily = 'Arial,sans-serif';
        controlText.style.fontSize = '12px';
        controlText.style.paddingLeft = '4px';
        controlText.style.paddingRight = '4px';
        controlText.innerHTML = '<b>Home<b>'
        controlUI.appendChild(controlText);

        // Setup click-event listener: simply set the map to London
        google.maps.event.addDomListener(controlUI, 'click', function() {
            map.setCenter(homePosition);
        });
    }

    function callOpenMap() {
        setTimeout("initialize()", 0);
    }
    
    $(function(){
        initialize();
    });
    
</script>

<div class="row-fluid">
    <div class="span12">
        <h3 class="heading">Bản đồ khách sạn</h3>
        <?php
        if (count($this->SuccessMsg) > 0) {
            echo '<div class="form_alert form_alert-info">' . current($this->SuccessMsg) . '</div>';
        }
        if (count($this->ErrorMsg) > 0) {
            echo '<div class="form_alert form_alert-error">' . current($this->ErrorMsg) . '</div>';
        }
        ?>
        <form name="form_useful" id="form_useful" method="post" action="">
            <div class="formSep" style="border: none">
                <div class="row-fluid">
                    <div class="span8">
                        <p><?php echo $this->HotelInfo['Hotel_Name'];?></p>
                        <p><?php echo $this->HotelInfo['Hotel_Address'];?></p>
                        <div id="map" style="width:800px;height:400px;"></div>
                        <p>Chọn và giữ chuột để cập nhật lại vị trí khách sạn.</p>
                    </div>
                </div>
            </div>

            <div class="form-actions">
                <input type="hidden" id="lat" name="lat" value="<?php echo $this->HotelInfo['Hotel_Map_Lat']; ?>" />
                <input type="hidden" id="lng" name="lng" value="<?php echo $this->HotelInfo['Hotel_Map_Lng']; ?>" />
                <input type="hidden" id="zoom" name="zoom" value="<?php echo $this->HotelInfo['Hotel_Map_Zoom']; ?>" />
                <button id="edit_confirm" class="btn btn-inverse" type="submit">Đồng ý chỉnh sửa</button>
            </div>
        </form>
    </div>                        
</div>                      