<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>ADMIN PANEL</title>
        <link rel="stylesheet" type="text/css" href="<?php echo _BACKEND_URL; ?>/css/style.css" />
        <script type="text/javascript" src="<?php echo _BACKEND_URL; ?>/js/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo _BACKEND_URL; ?>/css/niceforms-default.css" />

    </head>
    <body>
        <div id="main_container">
           <?php echo $this->layout()->content;?>
        </div>	
    </body>
</html>

