
<?php if (count($this->WarningMsg) > 0) { ?>
    <div class="warning_box">
        <?php echo current($this->WarningMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->SuccessMsg) > 0) { ?>
    <div class="valid_box">
        <?php echo current($this->SuccessMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->ErrorMsg) > 0) { ?>
    <div class="error_box">
        <?php echo current($this->ErrorMsg); ?>
    </div>
<?php } ?>
<div class="form">
    <form action="" method="post" class="niceform" name='frm' enctype="multipart/form-data">
        <fieldset>
            <dl>
                <dt><label for="email">Đường dẫn:</label></dt>
                <dd>
                    <input placeholder="Đường dẫn" type="text" name="Link" id="Link" size="34" style="width:350px" class="require" value="<?php echo $this->SeoKeyword['Link']; ?>" />
                    <br><span>(Từ khóa, miêu tả sẽ tương ứng với đường dẫn của Website)</span>
                </dd>
            </dl>
            <dl>
                <dt><label for="email">Tiêu đề (Title):</label></dt>
                <dd>
                    <input placeholder="Tiêu đề" type="text" name="Title" id="Title" size="34" style="width:350px" value="<?php echo $this->SeoKeyword['Title']; ?>" />
                    <br><span>(Tiêu đề trang phải là duy nhất trong toàn bộ Website)</span>
                </dd>
            </dl>
            <dl>
                <dt><label for="email">Từ khóa (Keywords):</label></dt>
                <dd>
                    <textarea placeholder="Từ khóa" name="Keyword" id="Keyword"><?php echo $this->SeoKeyword['Keyword']; ?></textarea>
                    <br><span>(Từ khóa của 1 đường dẫn Bản tin hoặc sản phẩm trong Website<br>
                        Sử dụng các từ khóa liên quan tới bài viết, độ dài khoảng 10 từ trở lên)</span>
                </dd>
            </dl>
            <dl>
                <dt><label for="email">Mô tả (Description):</label></dt>
                <dd>
                    <textarea placeholder="Mô tả" name="Description" id="Description"><?php echo $this->SeoKeyword['Description']; ?></textarea>
                    <br><span>(Mô tả của 1 đường dẫn Bản tin hoặc sản phẩm trong Website
                        Độ dài trong mô tả khoảng 140 kí tự, tránh nhồi nhét từ khóa(spam keywords))</span>
                </dd>
            </dl>
            <dl>
                <dt><label for="color">Hiển thị</label></dt>
                <dd>
                    <input <?php echo ($this->SeoKeyword['Status'] == 1) ? "checked='checked'" : ""; ?> type="radio" name="Status" id="Status_1" value="1" checked="checked" /><label for="Status_1" class="check_label">Có</label>
                    <input <?php echo ($this->SeoKeyword['Status'] == 0) ? "checked='checked'" : ""; ?> type="radio" name="Status" id="Status_0" value="0" /><label for="Status_0" class="check_label">Không</label>
                </dd>
            </dl>

            <dl class="submit">
                <a onclick="checkForm()" class="bt_blue"><span class="bt_blue_lft"></span><strong>Cập nhật</strong><span class="bt_blue_r"></span></a>
            </dl>
        </fieldset>
    </form>
</div>

<script>
        function checkForm() {
            var name = $("#Link").val();
            if (name == '') {
                alert('Vui lòng nhập Đường dẫn.');
                $("#Link").focus();
                return;
            }
            document.frm.submit();
        }
</script>