<div class="content-home">
	<h2>Welcome to your Admin Panel !</h2>
	Please use tabs menu to navigate into your admin panel ! 	
	<Br>
	<fieldset style="width: 200px;">
		<legend><img title="" alt="Your website" src="<?php echo _BACKEND_URL; ?>/images/tab-stats.gif"> Your website</legend>
		<p>Đối tác: <b><?php echo $this->partner->count; ?></b></p>
		<p>Khách sạn: <b><?php echo $this->hotel->count; ?></b></p>
	</fieldset>
</div>