<div class="row-fluid">
    <div class="span12">
        <h3 class="heading">Danh sách phòng</h3>
        <table class="table table-bordered table-striped table_vam" id="dt_enterprises">
            <thead>
                <tr>               
                    <th>Loại phòng</th>
					<th>Mã phòng</th>
					<th>Diên tích</th>
					<th>Sô ngươi</th>
                    <th>Ngày tạo</th>
                    <th>Trạng thái</th>
                    <th>Sửa</th
                </tr>
            </thead>
            <tbody>
                <?php $stt = 1;
                foreach ($this->Room as $v) {
                    ?>
                    <tr>
                        <td><?php echo $v['Room_Name']; ?></td>
						<td><?php echo $v['Room_Code']; ?></td>
						<td><?php echo $v['Room_Size']; ?></td>
						<td><?php echo $v['Room_MaxOccupancy']; ?></td>
                        <td><?php echo MyZend_Function::formatDateYMDHIS_DMYHIS($v['Room_Date_create']); ?></td>
                        <td><img class="status-img" id="status_<?php echo $v['Room_Id']; ?>" 
                                 src="<?php echo _BACKEND_URL . '/images/' . (($v['Room_Status'] == 1) ? 'icon_approve.png' : 'icon_unapprove.png'); ?>" /></td>
                        <td>
                            <a href="<?php echo _URL_HPARTNER . '/hotel-room/edit/id/' . $v['Room_Id']; ?>" class="sepV_a" title="Sửa"><i class="icon-pencil"></i></a>
                        </td>
                    </tr>
                    <?php $stt++;
                }
                ?>
                    <tr>
                        <td colspan="7">
                            <?php echo $this->paginationControl($this->page, 'Sliding', 'page.phtml', array('controller' => 'hotel-room')); ?>
                        </td>
                    </tr>
            </tbody>
        </table>
        
    </div>
</div>
