<!-- Maps marker-->
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script>
// The following example creates a marker in Stockholm, Sweden
// using a DROP animation. Clicking on the marker will toggle
// the animation between a BOUNCE animation and no animation.

	var latDefault = 14.060154519818523;
	var lngDefault = 108.27189977929686;
	var zoomDefault = 5;

	function initialize() {
		getPosition();
		var vietnam = new google.maps.LatLng(lat, lng);
		var parliament = new google.maps.LatLng(lat, lng);
		var marker;
		var map;

		var mapOptions = {
			zoom: zoom,
			center: vietnam
		};

		map = new google.maps.Map(document.getElementById('map'),
				mapOptions);

		marker = new google.maps.Marker({
			map: map,
			draggable: true,
			animation: google.maps.Animation.DROP,
			position: parliament
		});

		// Create a DIV to hold the control and call HomeControl()
		var homeControlDiv = document.createElement('div');
		var homeControl = new HomeControl(homeControlDiv, map);
		map.controls[google.maps.ControlPosition.TOP_RIGHT].push(homeControlDiv);

		google.maps.event.addListener(marker, 'click', function(event) {
			toggleBounce();
		});
		google.maps.event.addListener(marker, 'dragend', function(event) {
			$("#lat").val(event.latLng.lat());
			$("#lng").val(event.latLng.lng());
			$("#zoom").val(map.getZoom());

		});

		google.maps.event.addDomListener(marker, 'zoom_changed', function(event) {
			alert('test');
			$("#zoom").val(map.getZoom());
		});
	}

	function toggleBounce() {
		if (marker.getAnimation() != null) {
			marker.setAnimation(null);
		} else {
			marker.setAnimation(google.maps.Animation.BOUNCE);
		}
	}
	//google.maps.event.addDomListener(window, 'load', initialize);

	function getPosition() {
		var latInput = $("#lat").val();
		var lngInput = $("#lng").val();
		var zoomInput = $("#zoom").val();

		lat = latDefault;
		lng = lngDefault;
		zoom = zoomDefault;

		if (latInput != "") {
			lat = latInput;
		}
		if (lngInput != "") {
			lng = lngInput;
		}
		if (zoomInput != "") {
			zoom = parseInt(zoomInput);
		}
	}

	// Add a Home control that returns the user to London
	function HomeControl(controlDiv, map) {
		homePosition = new google.maps.LatLng(latDefault, lngDefault);
		controlDiv.style.padding = '5px';
		var controlUI = document.createElement('div');
		controlUI.style.backgroundColor = 'yellow';
		controlUI.style.border = '1px solid';
		controlUI.style.cursor = 'pointer';
		controlUI.style.textAlign = 'center';
		controlUI.title = 'Set map to London';
		controlDiv.appendChild(controlUI);
		var controlText = document.createElement('div');
		controlText.style.fontFamily = 'Arial,sans-serif';
		controlText.style.fontSize = '12px';
		controlText.style.paddingLeft = '4px';
		controlText.style.paddingRight = '4px';
		controlText.innerHTML = '<b>Home<b>'
		controlUI.appendChild(controlText);

		// Setup click-event listener: simply set the map to London
		google.maps.event.addDomListener(controlUI, 'click', function() {
			map.setCenter(homePosition);
		});
	}

	function callOpenMap() {
		setTimeout("initialize()", 0);
	}
</script>


<!-- Fancybox -->
<script type="text/javascript" src="<?php echo _BACKEND_URL; ?>/js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo _BACKEND_URL; ?>/fancybox/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="<?php echo _BACKEND_URL; ?>/fancybox/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo _BACKEND_URL; ?>/fancybox/fancybox/jquery.fancybox-1.3.4.css" media="screen" />


<script>
	$(function() {
		$(document).tooltip({
			items: "img",
			content: function() {
				var element = $(this);
				if (element.is("img")) {
					var text = element.attr("alt");
				}
				return text;
			}
		});
	});
</script>


<?php if (count($this->WarningMsg) > 0) { ?>
	<div class="warning_box">
		<?php echo current($this->WarningMsg); ?>
	</div>
<?php } ?>

<?php if (count($this->SuccessMsg) > 0) { ?>
	<div class="valid_box">
		<?php echo current($this->SuccessMsg); ?>
	</div>
<?php } ?>

<?php if (count($this->ErrorMsg) > 0) { ?>
	<div class="error_box">
		<?php echo current($this->ErrorMsg); ?>
	</div>
<?php } ?>

<div class="form">
    <form action="" enctype="multipart/form-data" method="post" class="niceform" name='frm'>
        <fieldset>
			<dl class="part_title">Thông tin cơ bản</dl>
            <dl class="col2">
                <dt><label>Tên khách sạn:</label></dt>
                <dd><input placeholder="Tên khách sạn" type="text" name="Name" id="Name" size="34" class="require" value="<?php echo $this->Hotel['Hotel_Name']; ?>" /></dd>
            </dl>

            <dl class="col2">
                <dt><label>Tỉnh/Thành:</label></dt>
                <dd>
                    <select placeholder="Tỉnh/Thành" name="Province" id="Province" class="require">
                        <option value="">&nbsp;</option>
						<?php foreach ($this->Province as $v) { ?>
							<option <?php echo ($this->Hotel['Province_Id'] == $v['Province_Id']) ? "selected='selected'" : ""; ?> value="<?php echo $v['Province_Id']; ?>"><?php echo $v['Province_Name']; ?></option>
						<?php } ?>
                    </select>
                </dd>
            </dl>

            <dl class="col2">
                <dt><label>Địa chỉ:</label></dt>
                <dd><input placeholder="Địa chỉ khách sạn" type="text" name="Address" id="Address" size="34" class="require" value="<?php echo $this->Hotel['Hotel_Address']; ?>" /></dd>
            </dl>

            <dl class="col2">
                <dt><label>Quận/Huyện:</label></dt>
                <dd>
                    <select placeholder="Quận/Huyện" name="District" id="District" class="require">
                        <option value="">&nbsp;</option>
						<?php foreach ($this->District as $v) { ?>
							<option <?php echo ($this->Hotel['District_Id'] == $v['District_Id']) ? "selected='selected'" : ""; ?> value="<?php echo $v['District_Id']; ?>"><?php echo $v['District_Name']; ?></option>
						<?php } ?>
                    </select>
                </dd>
            </dl>          
            <dl class="col2">
                <dt><label>Số sao:</label></dt>
                <dd>
                    <select name="Star" id="Star" class="require">
						<?php for ($i = 0; $i <= 5; $i++) { ?>
							<option <?php echo ($this->Hotel['Hotel_Star'] == $i) ? "selected='selected'" : ""; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
						<?php } ?>
                    </select>
                </dd>
            </dl>           
            <dl class="col2">
                <dt><label>Khu vực:</label></dt>
                <dd>
                    <select placeholder="Khu vực" name="Geo_Near" id="Geo_Near">
                        <option value="">&nbsp;</option>
						<?php foreach ($this->GeoNear as $v) { ?>
							<option <?php echo ($this->Hotel['Hotel_Geo_Near'] == $v['GeoNear_Id']) ? "selected='selected'" : ""; ?> value="<?php echo $v['GeoNear_Id']; ?>"><?php echo $v['GeoNear_Name']; ?></option>
						<?php } ?>
                    </select>
                </dd>
            </dl>
            <dl class="col2">
                <dt><label>Đối tác:</label></dt>
                <dd>
                    <select placeholder="Đối tác" name="Partner" id="Partner" class="require">
                        <option value="">&nbsp;</option>
						<?php foreach ($this->Partner as $v) { ?>
							<option <?php echo ($this->Hotel['User_Id'] == $v['User_Id']) ? "selected='selected'" : ""; ?> value="<?php echo $v['User_Id']; ?>"><?php echo $v['User_Name']; ?></option>
						<?php } ?>
                    </select>
                </dd>
            </dl>  
            <dl class="col2">
                <dt><label>Số phòng:</label></dt>
                <dd>
                    <input placeholder="Số phòng" type="text" name="Room" id="Room" size="34" value="<?php echo $this->Hotel['Hotel_Room']; ?>" />
                </dd>
            </dl>
            <dl class="col2">
                <dt><label>Loại khách sạn:</label></dt>
                <dd>
                    <select placeholder="Loại khách sạn" name="HotelType" id="HotelType" class="require">
                        <option value="">&nbsp;</option>
						<?php foreach ($this->HotelType as $v) { ?>
							<option <?php echo ($this->Hotel['HotelType_Id'] == $v['HotelType_Id']) ? "selected='selected'" : ""; ?> value="<?php echo $v['HotelType_Id']; ?>"><?php echo $v['HotelType_Name']; ?></option>
						<?php } ?>
                    </select>
                </dd>
            </dl>
            <dl class="col2">
                <dt><label>Điện thoại chính:</label></dt>
                <dd>
                    <input placeholder="Điện thoại chính" type="text" name="Hotel_Phone" id="Hotel_Phone" size="34" value="<?php echo $this->Hotel['Hotel_Phone']; ?>" class="require" />
                </dd>
            </dl>
            <dl class="col2">
                <dt><label>Số fax:</label></dt>
                <dd>
                    <input placeholder="Số fax" type="text" name="Hotel_Fax" id="Hotel_Fax" size="34" value="<?php echo $this->Hotel['Hotel_Fax']; ?>" />
                </dd>
            </dl>
            <dl class="col2">
                <dt><label>Website:</label></dt>
                <dd>
                    <input placeholder="Website" type="text" name="Hotel_Website" id="Hotel_Website" size="34" value="<?php echo $this->Hotel['Hotel_Website']; ?>" />
                </dd>
            </dl>
            <dl class="col2">
                <dt><label>Hoa hồng (%):</label></dt>
                <dd>
                    <input placeholder="Hoa hồng nhà cung cấp trả cho website" type="text" name="Hotel_Commission" id="Hotel_Commission" size="34" value="<?php echo $this->Hotel['Hotel_Commission']; ?>" />
                </dd>
            </dl>

			<dl class="col2">
                <dt><label>Thuế (%):</label></dt>
                <dd>
                    <input placeholder="Thuế website trả cho nhà cung cấp" type="text" name="Hotel_Tax" id="Hotel_Tax" size="34" value="<?php echo $this->Hotel['Hotel_Tax']; ?>" />
                </dd>
            </dl>

			<dl class="part_title">Trẻ em và giường phụ</dl>
			<dl class="col2">
                <dt><label>Trẻ nhỏ tính đến:</label></dt>
                <dd>
                    <select name="InfantAge" id="InfantAge" style="width: 180px">
						<?php for ($i = 0; $i <= 5; $i++) { ?>
							<option <?php echo ($this->Hotel['Hotel_InfantAge'] == $i) ? "selected='selected'" : ""; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
						<?php } ?>
                    </select> tuổi
                </dd>
            </dl> 
			<dl class="col2">
                <dt><label>Trẻ lớn tính từ:</label></dt>
                <dd>
                    <label id="span_InfantAge"><?php echo $this->Hotel['Hotel_InfantAge'] + 1; ?></label> &nbsp;Cho đến
                    <select name="ChildAgeTo" id="ChildAgeTo" style="width: 110px">
						<?php for ($i = 0; $i <= 21; $i++) { ?>
							<option <?php echo ($this->Hotel['Hotel_ChildAgeTo'] == $i) ? "selected='selected'" : ""; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
						<?php } ?>
                    </select> tuổi
                </dd>
            </dl>
			<dl class="col2">
                <dt><label>Số tuổi khách tối thiểu:</label></dt>
                <dd>
                    <select name="MinGuestAge" id="MinGuestAge" style="width: 180px">
						<?php for ($i = 0; $i <= 21; $i++) { ?>
							<option <?php echo ($this->Hotel['Hotel_MinGuestAge'] == $i) ? "selected='selected'" : ""; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
						<?php } ?>
                    </select> tuổi
                </dd>
            </dl>
            <dl class="col2">
                <dt><label>Giường phụ bắt buộc cho người từ:</label></dt>
                <dd>
                    <select name="MaxChildAge" id="MaxChildAge" style="width: 180px">
						<?php for ($i = 0; $i <= 21; $i++) { ?>
							<option <?php echo ($this->Hotel['Hotel_MaxChildAge'] == $i) ? "selected='selected'" : ""; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
						<?php } ?>
                    </select> tuổi
                </dd>
            </dl>
            <dl class="col2">
                <dt><label>Trẻ em ở miễn phí:</label></dt>
                <dd>
                    <input type="radio" name="ChildStayFree" value="1" id="ChildStayFree1" <?php echo ($this->Hotel['Hotel_ChildStayFree'] == 1) ? "checked='checked'" : ""; ?>  /> <label for="ChildStayFree1">Có</label>
                    &nbsp;&nbsp;&nbsp;
                    <input type="radio" name="ChildStayFree" value="0" id="ChildStayFree0" <?php echo ($this->Hotel['Hotel_ChildStayFree'] == 0) ? "checked='checked'" : ""; ?> /> <label for="ChildStayFree0">Không</label>
                </dd>
            </dl>
			<dl class="part_title">Bản đồ và Tiện ích</dl>
            <dl>
                <dt><label>Bản đồ:</label></dt>
                <dd>
                    <a onclick="callOpenMap()" id="link1" href="#map">Chọn địa điểm</a>
                    <img id="warning_remap" style="display: none" alt="Vui lòng định hướng lại bản đồ khi thay đổi Tỉnh/Thành" src="<?php echo _BACKEND_URL . '/images/warning_icon.png'; ?>" />
                    <div style="display: none;">
                        <div id="map" style="width:800px;height:400px;"></div>
                    </div>
                    <input type="hidden" id="lat" name="lat" value="<?php echo $this->Hotel['Hotel_Map_Lat']; ?>" />
                    <input type="hidden" id="lng" name="lng" value="<?php echo $this->Hotel['Hotel_Map_Lng']; ?>" />
                    <input type="hidden" id="zoom" name="zoom" value="<?php echo $this->Hotel['Hotel_Map_Zoom']; ?>" />
                </dd>
            </dl>
            <dl>
                <dt><label>Tiện ích:</label></dt>
                <dd>
                    <ul class="facilities">
						<?php $Facilities = explode(',', $this->Hotel['Hotel_Facilities']); ?>
						<?php foreach ($this->Facilities as $v) { ?>  
							<li>
								<input <?php echo ($Facilities && in_array($v['Facilities_Id'], $Facilities)) ? "checked='checked'" : ""; ?> id="facilities_<?php echo $v['Facilities_Id']; ?>" type="checkbox" name="Facilities[<?php echo $v['Facilities_Id']; ?>]" value="<?php echo $v['Facilities_Id']; ?>" /> <label for="facilities_<?php echo $v['Facilities_Id']; ?>"><?php echo $v['Facilities_Name']; ?></label>
							</li>
						<?php } ?>
                    </ul>
                </dd>
            </dl>
			<dl class="part_title">Hình ảnh</dl>
            <dl>
                <dl style="width:1000px">
                    <a id="link2" href="<?php echo _URL_ADMIN . '/upload-image'; ?>">Chọn hình ảnh upload</a>
                    <div id="showListImage" class="showListImage" style='width: 1030px'>
						<?php echo '<ul id="sortable">'; ?>
						<?php foreach ($this->listImage as $v) { ?>
							<?php
							echo '<li id="li_imgListHotel_' . $v['HotelPicture_Id'] . '" class="ui-state-default">
									<div class="del_img" onclick="delPictureHotel(' . $v['HotelPicture_Id'] . ', \'' . $v['HotelPicture_Name'] . '\', this)">X</div>
									<table class="table_img_list" id="table_img_listHotel_' . $v['HotelPicture_Id'] . '">';
							echo '<tr><td class="img">';
							?>
							<img src="<?php echo MyZend_Function::thumb(_PICTURE_HOTEL_URL . '/' . $v['HotelPicture_Name'], 106, 106); ?>" class="imgList" />
							<?php
							echo '</td></tr>';
							echo '<tr><td>';
							echo '<select name="pictureview_imgListHotel[' . $v['HotelPicture_Id'] . ']">';
							echo '<option value="0" ' . (($v['PictureView_Id'] == 0) ? "selected=\"selected\"" : "") . '>Chọn tiêu đề ảnh</option>';
							foreach ($this->PictureView as $vv) {
								echo '<option ' . (($vv['PictureView_Id'] == $v['PictureView_Id']) ? "selected=\"selected\"" : "") . ' value="' . $vv['PictureView_Id'] . '">' . $vv['PictureView_Name'] . '</option>';
							}
							echo '</select>';
							echo '</td></tr>';
							echo '<tr><td><select name="status_imgListHotel[' . $v['HotelPicture_Id'] . ']"><option value="1" ' . (($v['HotelPicture_Status'] == 1) ? "selected='selected'" : "") . '>Hiển thị</option><option value="0" ' . (($v['HotelPicture_Status'] == 0) ? "selected='selected'" : "") . '>Ẩn</option></select></td></tr>';
							echo '<tr><td><input placeholder="Tiêu đề ảnh" type="text" name="title_imgListHotel[' . $v['HotelPicture_Id'] . ']" value="' . $v['HotelPicture_Title'] . '" /></td></tr>';
							echo '</table><input type="hidden" name="position_imgListHotel[' . $v['HotelPicture_Id'] . ']" class="position_imgList" value="' . $v['HotelPicture_Position'] . '" /></li>';
							?>
						<?php } ?>
						<?php echo '</ul>'; ?>
                    </div>
                    <div style="display: none;">
                        <div id="uploadImage" class="uploadImage">

                        </div>
                    </div>
                </dl>
            </dl>
			<dl class="part_title">Thông tin hữu ích:</dl>
            <dl>
                <dl style="width: 1000px; padding-left: 100px;">
                    <ul class="useful">
						<?php $Useful = json_decode(str_replace("&quot;", '"', $this->Hotel['Hotel_Useful']), TRUE); ?>
						<?php foreach ($this->Useful as $v) { ?>
							<li>                                   
								<ul>
									<li><?php echo $v['Useful_Name']; ?></li>
									<li>
										<input type="text" value="<?php echo $Useful[$v['Useful_Id']]; ?>" style="width: 150px" name="Useful[<?php echo $v['Useful_Id']; ?>]" id="Useful_<?php echo $v['Useful_Id']; ?>" /> 
									</li>
								</ul>
							</li>
						<?php } ?>
                    </ul>
                </dl>
            </dl>
			<dl class="part_title">Mô tả:</dl>
            <dl>
                <dl style="width: 1000px; padding-left: 100px;">
                    <textarea placeholder="Mô tả" id="Description" name="Description" class="Editor_Body"><?php echo $this->Hotel['Hotel_Description']; ?></textarea>
                </dl>
            </dl>
			<dl class="part_title">Chính sách:</dl>
            <dl>
                <dl style="width: 1000px; padding-left: 100px;">
                    <textarea placeholder="Chính sách" id="Rule_Order" name="Rule_Order" class="Editor_Body"><?php echo $this->Hotel['Hotel_Rule_Order']; ?></textarea>
                </dl>
            </dl>

            <dl>
                <dt><label for="color">Trạng thái</label></dt>
                <dd>
                    <select style="width: 100px" name="Status" id="Status">
                        <option <?php echo ($this->Hotel['Hotel_Status'] == 1) ? "selected='selected'" : ""; ?> value="1">Hoạt động</option>
                        <option <?php echo ($this->Hotel['Hotel_Status'] == 0) ? "selected='selected'" : ""; ?> value="0">Tạm dừng</option>
						<?php if ($this->Hotel['Hotel_Status'] == 2) {?>
						<option <?php echo ($this->Hotel['Hotel_Status'] == 2) ? "selected='selected'" : ""; ?> value="2">Chờ duyệt</option>
						<?php }?>
					</select>
                </dd>
            </dl>

            <dl class="submit">
                <a onclick="checkForm()" class="bt_blue"><span class="bt_blue_lft"></span><strong>Cập nhật</strong><span class="bt_blue_r"></span></a>
            </dl>

        </fieldset>
    </form>
</div>

<script>
	$.noConflict();
	jQuery(document).ready(function() {
		jQuery("#link1").fancybox();
		jQuery("#link2").fancybox({
			'width': '75%',
			'height': '75%',
			'autoScale': false,
			'transitionIn': 'none',
			'transitionOut': 'none',
			'type': 'iframe',
			'onClosed': function() {
				$.post("<?php echo _URL_ADMIN . '/hotel/get-image-list-all'; ?>", {token: '<?php echo $this->Token; ?>'}, function(result) {
					eval(result);
					$("#showListImage").html("");
					var table_img_list = '<ul id="sortable">';
					var position;
					$.each(data.hotel, function(i, item) {
						var selected1 = (item.HotelPicture_Status == 1) ? "selected='selected'" : "";
						var selected0 = (item.HotelPicture_Status == 0) ? "selected='selected'" : "";
						table_img_list += '<li id="li_imgListHotel_' + item.HotelPicture_Id + '" class="ui-state-default"><div class="del_img" onclick="delPictureHotel(' + item.HotelPicture_Id + ', \'' + item.HotelPicture_Name + '\', this)">X</div><table class="table_img_list" id="table_img_listHotel_' + item.HotelPicture_Id + '">';
						table_img_list += '<tr><td class="img">';
						table_img_list += '<img  class="imgList" src="<?php echo _THUMB_URL . "?src=" . _PICTURE_HOTEL_URL; ?>/' + item.HotelPicture_Name + '&amp;w=106&amp;h=106" />';
						table_img_list += '</td></tr>';
						table_img_list += '<tr><td>';
						table_img_list += '<select name="pictureview_imgListHotel[' + item.upload_id + ']">';
						table_img_list += '<option value="0" ' + ((item.PictureView_Id == 0) ? "selected=\"selected\"" : "") + '>Chọn tiêu đề ảnh</option>';
<?php foreach ($this->PictureView as $v) { ?>
							table_img_list += '<option ' + ((item.PictureView_Id == <?php echo $v['PictureView_Id']; ?>) ? "selected=\"selected\"" : "") + ' value="<?php echo $v['PictureView_Id']; ?>"><?php echo $v['PictureView_Name']; ?></option>';
<?php } ?>
						table_img_list += '</select>';
						table_img_list += '</td></tr>';
						table_img_list += '<tr><td><select name="status_imgListHotel[' + item.HotelPicture_Id + ']"><option value="1" ' + selected1 + '>Hiển thị</option><option value="0" ' + selected0 + '>Ẩn</option></select></td></tr>';
						table_img_list += '<tr><td><input placeholder="Tiêu đề ảnh" type="text" name="title_imgListHotel[' + item.HotelPicture_Id + ']" value="' + item.HotelPicture_Title + '"/></td></tr>';
						table_img_list += '</table><input type="hidden" name="position_imgListHotel[' + item.HotelPicture_Id + ']" class="position_imgList" value="' + item.HotelPicture_Position + '" /></li>';
						position = parseInt(item.HotelPicture_Position);
					});
					$.each(data.temp, function(i, item) {
						position = (position + 1);
						table_img_list += '<li id="li_imgList_' + item.upload_id + '" class="ui-state-default"><div class="del_img" onclick="delPicTemp(' + item.upload_id + ', \'' + item.image_name + '\', this)">X</div><table class="table_img_list" id="table_img_list_' + item.upload_id + '">';
						table_img_list += '<tr><td class="img">';
						table_img_list += '<img class="imgList" src="<?php echo _THUMB_URL . "?src=" . _PICTURE_HOTEL_TEMP_URL; ?>/' + item.image_name + '&amp;w=106&amp;h=106" />';
						table_img_list += '</td></tr>';
						table_img_list += '<tr><td>';
						table_img_list += '<select name="pictureview_imgList[' + item.upload_id + ']">';
						table_img_list += '<option value="0">Chọn tiêu đề ảnh</option>';
<?php foreach ($this->PictureView as $v) { ?>
							table_img_list += '<option value="<?php echo $v['PictureView_Id']; ?>"><?php echo $v['PictureView_Name']; ?></option>';
<?php } ?>
						table_img_list += '</select>';
						table_img_list += '</td></tr>';
						table_img_list += '<tr><td><select name="status_imgList[' + item.upload_id + ']"><option value="1">Hiển thị</option><option value="0">Ẩn</option></select></td></tr>';
						table_img_list += '<tr><td><input placeholder="Tiêu đề ảnh" type="text" name="title_imgList[' + item.upload_id + ']" /></td></tr>';
						table_img_list += '</table><input type="hidden" name="position_imgList[' + item.upload_id + ']" class="position_imgList" value="' + position + '" /></li>';
					});
					table_img_list += '</ul>';
					$("#showListImage").append(table_img_list);
					sortImg();
				});
			}
		});
	});
	jQuery(document).ready(function() {
		sortImg();
	});

	function sortImg() {
		$("#sortable").sortable({
			stop: function(event, ui) {
				$.map($(this).find('li'), function(el) {
					$("#" + el.id).find(".position_imgList").val($(el).index());
				});
			}
		});
		$("#sortable").disableSelection();
	}

	function delPicTemp(uploadid, imagename, thIs) {
		if (confirm('Bạn có chắc chắn muốn xóa?')) {
			$.post("<?php echo _URL_ADMIN . '/hotel/del-pic-temp'; ?>", {id: uploadid, image: imagename}, function(data) {
				$("#li_imgList_" + uploadid).remove();
			});
		}
	}

	function delPictureHotel(id, imagename, thIs) {
		if (confirm('Bạn có chắc chắn muốn xóa?')) {
			$.post("<?php echo _URL_ADMIN . '/hotel/del-pic-hotel'; ?>", {id: id, image: imagename}, function(data) {
				$("#li_imgListHotel_" + id).remove();
			});
		}
	}

	function checkForm() {
		var name = $("#Name").val();
		var address = $("#Address").val();
		var province = $("#Province").val();
		var district = $("#District").val();
		var partner = $("#Partner").val();
		var star = $("#Star").val();
		var price = $("#Price").val();
		var hoteltype = $("#HotelType").val();
		var hotelphone = $("#Hotel_Phone").val();
		if (name == '') {
			alert('Vui lòng nhập Tên khách sạn.');
			$("#Name").focus();
			return;
		}
		if (star == '') {
			alert('Vui lòng nhập Số sao.');
			$("#Star").focus();
			return;
		}
		if (address == '') {
			alert('Vui lòng nhập Địa chỉ.');
			$("#Address").focus();
			return;
		}
		if (province == '') {
			alert('Vui lòng chọn Tỉnh/Thành.');
			return;
		}
		if (district == '') {
			alert('Vui lòng chọn Quận/Huyện.');
			return;
		}
		if (partner == '') {
			alert('Vui lòng chọn Đối tác.');
			return;
		}
		if (hoteltype == '') {
			alert('Vui lòng chọn Loại khách sạn.');
			return;
		}
		if (hotelphone == '') {
			alert('Vui lòng nhập Số điện thoại chính.');
			$("#Hotel_Phone").focus();
			return;
		}
		document.frm.submit();

	}


	$("#Province").change(function() {

		$("#District").attr("disabled", "disabled");
		$("#Geo_Near").attr("disabled", "disabled");

		$.post("<?php echo _URL . '/iadm/hotel/mapping-province/'; ?>", {provinceId: $(this).val()}, function(result) {
			var strOptionDistrict;
			var data = eval(result);

			strOptionDistrict = "<option value=''>&nbsp;</option>";
			$.each(data, function(i, item) {
				strOptionDistrict += "<option value='" + item.District_Id + "'>" + item.District_Name + "</option>";
				$("#lat").val(item.Province_Lat);
				$("#lng").val(item.Province_Lng);
				$("#zoom").val(item.Province_Zoom);
			});
			$("#warning_remap").show();
			$("#District").removeAttr("disabled");
			$("#District").html(strOptionDistrict);
		});

		$.post("<?php echo _URL . '/iadm/hotel/mapping-geonear/'; ?>", {provinceId: $(this).val()}, function(result) {
			var strOptionGeoNear;
			var data = eval(result);

			strOptionGeoNear = "<option value=''>&nbsp;</option>";
			$.each(data, function(i, item) {
				strOptionGeoNear += "<option value='" + item.GeoNear_Id + "'>" + item.GeoNear_Name + "</option>";
			});
			$("#Geo_Near").removeAttr("disabled");
			$("#Geo_Near").html(strOptionGeoNear);
		});

	});
	$("#InfantAge").change(function() {
		$("#span_InfantAge").html(parseInt($(this).val()) + 1);
	});
</script>

