          
<?php if (count($this->WarningMsg) > 0) { ?>
    <div class="warning_box">
        <?php echo current($this->WarningMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->SuccessMsg) > 0) { ?>
    <div class="valid_box">
        <?php echo current($this->SuccessMsg); ?>
    </div>
<?php } ?>

<?php if (count($this->ErrorMsg) > 0) { ?>
    <div class="error_box">
        <?php echo current($this->ErrorMsg); ?>
    </div>
<?php } ?>      

<form name="frsearch" action="<?php echo _URL_ADMIN . '/member';?>" method="post">
    <fieldset class="fr-search">
        <legend>Tìm kiếm</legend>
        <table>
            <tr>
                <td style="width: 70px;" align="right">Email</td>
                <td><input name="EmailSearch" placeholder="Email" type="text" value="<?php echo $this->search['EmailSearch'];?>" /></td>
                <td align="right">Trạng thái</td>
                <td>
                    <select name="StatusSearch">
                        <option value="">Tất cả</option>
                        <option value="1" <?php echo ($this->search['StatusSearch'] == "1") ? "selected='selected'" : "";?>>Hoạt động</option>
                        <option value="0" <?php echo ($this->search['StatusSearch'] == "0") ? "selected='selected'" : "";?>>Tạm dừng</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <input type="hidden" name="typeAction" value="search" />
                    <a onclick="document.frsearch.submit()" class="bt_green"><span class="bt_green_lft"></span><strong>Tìm kiếm</strong><span class="bt_green_r"></span></a>
                </td>
            </tr>
        </table>
    </fieldset>
</form>

<form action="<?php echo _URL_ADMIN . '/member/delete'; ?>" name='frm' method='post'>
    <input type="hidden" name="typeAction" value="index" />
    <table id="rounded-corner">
        <thead>
            <tr>
                <th scope="col" class="rounded-company"><input type="checkbox" name="checkAll" id="checkAll" value="" /></th>
                <th scope="col" class="rounded" align="center">STT</th>
                <th scope="col" class="rounded">User</th>
                <th scope="col" class="rounded">Email</th>
                <th scope="col" class="rounded">Ngày tạo</th>
                <th scope="col" class="rounded">Trạng thái</th>
                <th scope="col" class="rounded">Sửa</th>
                <th scope="col" class="rounded-q4">Xóa</th>
            </tr>
        </thead>
        <?php if (count($this->listMember) > 0) { ?>
            <tfoot>
                <tr>
                    <td colspan="7" class="rounded-foot-left"><em>Hiển thị <?php echo $this->fromItem; ?> đến <?php echo $this->toItem; ?> / <?php echo $this->countMemberAll; ?> kết quả</em></td>
                    <td class="rounded-foot-right">&nbsp;</td>

                </tr>
            </tfoot>
            <tbody>
                <?php $i = $this->fromItem;
                foreach ($this->listMember as $v) {
                    ?>
                    <tr>                 
                        <td><input type="checkbox" name="checkboxDel[]" value="<?php echo $v['User_Id']; ?>" /></td>
                        <td align="center"><?php echo $i;?></td>
                        <td><?php echo $v['User_Name']; ?></td>
                        <td><?php echo $v['User_Email']; ?></td>
                        <td><?php echo MyZend_Function::formatDateYMDHIS_DMYHIS($v['User_DateCreate']); ?></td>
                        <td>
                            <img class="status-img" id="status_<?php echo $v['User_Id']; ?>" 
                                 onclick="updateStatus(<?php echo $v['User_Id']; ?>)" 
                                 src="<?php echo _BACKEND_URL . '/images/' . (($v['User_Status'] == 1) ? 'icon_approve.png' : 'icon_unapprove.png'); ?>" />
                        </td>
                        <td><a href="<?php echo _URL_ADMIN . '/member/edit/id/' . $v['User_Id']; ?>"><img src="<?php echo _BACKEND_URL; ?>/images/user_edit.png" alt="" title="" border="0" /></a></td>
                        <td><a href="<?php echo _URL_ADMIN . '/member/delete/id/' . $v['User_Id']; ?>" class="ask"><img src="<?php echo _BACKEND_URL; ?>/images/trash.png" alt="" title="" border="0" /></a></td>
                    </tr>
            <?php $i++;} ?>
            </tbody>
<?php } else { ?>
            <tr>
                <td colspan="8" class="result">
                    <div class='no-result'>Không tìm thấy kết quả</a>
                </td>
            </tr>
<?php } ?>
    </table>
</form>
<a href="<?php echo _URL_ADMIN . '/member/add'; ?>" class="bt_green"><span class="bt_green_lft"></span><strong>Thêm</strong><span class="bt_green_r"></span></a>
<a onclick="checkForm()" class="bt_red"><span class="bt_red_lft"></span><strong>Xóa</strong><span class="bt_red_r"></span></a> 
<?php echo $this->paginationControl($this->page, 'Sliding', 'page.phtml', array('controller' => 'member')); ?>

<script>
                                     function checkForm() {
                                         var checkValue = $("input[name='checkboxDel[]']:checked").length;
                                         if (checkValue == 0) {
                                             alert('Vui lòng chọn dòng cần xóa.');
                                             return false;
                                         }
                                         if (confirm('Bạn có chắc chắn muốn xóa?')) {
                                             document.frm.submit();
                                         }
                                     }

                                     function updateStatus(id) {
                                         $.post('<?php echo _URL_ADMIN . '/member/updatestatus/'; ?>', {id: id, table: '<?php echo _PREFIX; ?>user', statusName: 'User_Status', idName: 'User_Id'}, function(result) {
                                             if (result == 1) {
                                                 $("#status_" + id).attr("src", "<?php echo _BACKEND_URL . '/images/icon_approve.png'; ?>");
                                             } else {
                                                 $("#status_" + id).attr("src", "<?php echo _BACKEND_URL . '/images/icon_unapprove.png'; ?>");
                                             }
                                         })
                                     }
</script>